---
- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  openssl_dhparam:
    path: /etc/ssl/dhparams.pem
  when: use_https
  become: yes

- name: Add nodesjs ppa
  become: yes
  shell: "curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -"

- name: Install required packages
  become: yes
  apt:
    name:
      - libldap2-dev
      - libsasl2-dev
      - zlib1g-dev
      - make
      - build-essential
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - liblzma-dev
      - libffi-dev
      - git
      - python3-dateutil
      - ttf-bitstream-vera
      - redis-server
      - nodejs
      - python3-pip
      - libpangocairo-1.0-0
    state: present
    update_cache: true

- include_role:
    name: geerlingguy.supervisor
    apply:
      become: yes

- name: Include certbot role
  include_role:
    name: geerlingguy.certbot
    apply:
      become: yes
  when: install_certbot

- name: Install extension for future db
  shell: "psql -d 'template1' -c \"CREATE EXTENSION IF NOT EXISTS unaccent;\""
  become: yes
  become_user: postgres

- name: Install extension for current db
  shell: "psql -d 'happyschool' -c \"CREATE EXTENSION IF NOT EXISTS unaccent;\""
  become: yes
  become_user: postgres

- name: Get HappySchool
  git:
    repo: "https://github.com/ISLNamur/happyschool"
    dest: "{{ happyschool_home }}"

- pip:
    name: pipenv
    executable: pip3
    extra_args: --user

- name: Check if pyenv is installed
  stat:
    path: "/home/{{ ansible_user }}/.pyenv"
  register: pyenv_dir
  
- name: Install pyenv
  shell: "curl https://pyenv.run | bash"
  when: not pyenv_dir.stat.exists

- name: Update pyenv
  shell: ~/.pyenv/bin/pyenv update
  when: pyenv_dir.stat.exists

- name: Run a pipenv install
  shell: "PIPENV_YES=1 ~/.local/bin/pipenv install"
  args:
      chdir: "{{ happyschool_home }}"

- name: Install npm packages
  npm:
    path: "{{ happyschool_home }}"

- name: write the happyschool config file
  template:
    src: templates/settings.py.j2
    dest: "{{ happyschool_home }}/happyschool/settings.py"

- name: Create and update database tables
  command: "~/.local/bin/pipenv run ./manage.py migrate"
  args:
      chdir: "{{ happyschool_home }}"

- name: Collect static files
  command: "~/.local/bin/pipenv run ./manage.py collectstatic --noinput"
  args:
    chdir: "{{ happyschool_home }}"

- name: Build js bundles
  command: "./node_modules/.bin/webpack --config webpack.prod.js"
  args:
    chdir: "{{ happyschool_home }}"
  notify: "restart supervisor"

- name: Check if superuser is created
  command: '~/.local/bin/pipenv run ./manage.py shell --command="from django.contrib.auth.models import User; print(User.objects.filter(is_superuser=True).count())"'
  args:
    chdir: "{{ happyschool_home }}"
  register: is_superuser

- name: Create superuser
  command: "~/.local/bin/pipenv run ./manage.py shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('{{ happyschool_admin }}', '', '{{ happyschool_password }}')\""
  args:
    chdir: "{{ happyschool_home }}"
  when: "'0' == is_superuser.stdout"

- name: Create groups
  command: "~/.local/bin/pipenv run ./manage.py creategroups"
  args:
    chdir: "{{ happyschool_home }}"
